### ISSUE TITLE
How to set the flag connect_tools_all ?

### ISSUE THREAD

**Issue by avaa999** [Boey-li/AdaptiGraph#10]
Hi! Boey. Thank you for providing such a beautiful work! I noticed in the "construct_edges_from_state"function in _graph.py_ that there is a line of code that reads:
`if connect_tools_all:
    adj_matrix[obj_tool_mask_1] = 0
    adj_matrix[obj_tool_mask_2] = 1
    adj_matrix[tool_mask_12] = 0  # avoid tool to tool relations`
I would like to understand why `connect_tools_all `is set to _False_. And in what scenarios would it be more beneficial to set `connect_tools_all` to  _True_? Thank you for your time !

**Comment by Boey-li** [comment]
Hi, the `connect_tools_all` variable is used to link all object particles to the tool particle, rather than basing the connection on spatial distance. Typically, this is set to _False_ because the intuition is that the tool primarily affects the dynamics of nearby object particles.

However, we apply this variable in the _**cloth**_ case because cloth occupies a larger spatial area, and the default object-tool edge construction method struggles to learn the dynamics due to slow message passing. In this scenario, connecting all cloth particles to the tool effectively transmits the action message to distant object particles.

I hope this explanation clarifies things!

**Comment by avaa999** [comment]
Thank you for your reply, that makes a lot of sense!
