### ISSUE TITLE
State not included in Particle Encoder

### ISSUE THREAD

**Issue by AnnabellaMacaluso** [Boey-li/AdaptiGraph#2]
Hi, I was looking at the training script and noticed for all tasks that `model_config[state_dim]` is set to zero always. Is this intended? I was under the impression that past state information is used to train the particle encoder from the paper. Are there advantages/disadvantages to using state information in the particle encoder? Any clarification would be appreciated. Thank you!

**Comment by kywind** [comment]
Hi, thanks for the question. 

State information is necessary for training the dynamics model. In our tasks, they are added to the relation encoder instead of the particle encoder. As mentioned in the 'translation equivariance' paragraph in the paper, we pass the relative position difference between the receiver and sender particles, in the current frame and history frames, to the relation encoder, instead of passing absolute positions to the particle encoder in order to achieve translation equivariance. This is by setting `model_config[rel_distance_dim]` to 3 and `model_config[state_dim]` to 0. 

If `model_config[state_dim]` is set to 3 and `model_config[rel_distance_dim]` is set to 0, then the particle encoder will use past state information. This will reduce some computation (as the number of relations is typically larger than the number of vertices), but loses the translation equivariance.

**Comment by AnnabellaMacaluso** [comment]
This makes sense, thank you!
