### ISSUE TITLE
About the frame_pairs and raw eef_states

### ISSUE THREAD

**Issue by CAN-Lee** [Boey-li/AdaptiGraph#4]
Hi @Boey-li ,

Thanks for your works.

I am a little confused about the frame_pairs resulted from preprocessing data. The codes show that the .txt files store frame index, where the number of rows is equal to the number of pushes. Then, I would like to know the meaning of the number of columns.

![微信截图_20240827165439](https://github.com/user-attachments/assets/d9b3d4ff-cbb9-47ea-b302-b4a39bf231fe)

Thanks

Can

**Comment by CAN-Lee** [comment]
OK, I found that the number of columns is equal to the sum of n_his plus n_future

**Comment by CAN-Lee** [comment]
I noticed that the shape of raw end-effector states is (T, N_eef, 14). The codes show that eef_positions(shape:3) and eef_quaternion(shape: 4) are stored in states. I would like to know what is the meaning of 14 ? 

'eef_states': raw end effector states (T, N_eef, 14) float32

![微信截图_20240827233309](https://github.com/user-attachments/assets/550f3264-d711-4a20-835a-b7b89c1acb53)


Many thanks.

**Comment by Boey-li** [comment]
Hello, 

1. The preprocessing is to separate the raw data into prediction sequences, i.e., `n_his + n_future`. As described in the paper, we use the history information to implicitly encode the velocity information and predict multiple time steps forward to regularize the trainng and stabilize long-horizon future predictions. 

2. You can find the robot states information [here](https://github.com/Boey-li/AdaptiGraph/blob/main/src/sim/sim_env/robot_env.py) (line 91-104), the raw end-effector states is `[curr_positions (3), pre_positions (3), curr_orientation (4), pre_orientation (4)]`, but the pre_positions and pre_orientation are the same as the current's in our case. It does not matter since we only extract current positions and orientations in the [preprocessing](https://github.com/Boey-li/AdaptiGraph/blob/main/src/dynamics/preprocess/preprocess.py) (line 44-45) for end-effector particles.

**Comment by CAN-Lee** [comment]
Really appreciate your help. Thanks
